# Generated by Django 6.0.2 on 2026-02-23 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gpu_count', models.IntegerField(default=0)),
                ('gpu_type', models.CharField(blank=True, max_length=50)),
                ('ib_band', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('master', 'Master'), ('worker', 'Worker'), ('storage', 'Storage'), ('gpu', 'GPU'), ('network', 'Network')], max_length=20)),
                ('server_model', models.CharField(max_length=100)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('service_tag', models.CharField(max_length=50, unique=True)),
                ('idrac_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('idrac_username', models.CharField(blank=True, max_length=50)),
                ('idrac_password', models.CharField(blank=True, max_length=50)),
                ('bmc_mac_address', models.CharField(blank=True, max_length=17)),
                ('pxe_mac_address', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='dashboard.cluster')),
            ],
            options={
                'ordering': ['cluster', 'role', 'server_model'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('external_site', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('service_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='dashboard.server', to_field='service_tag')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
