# Generated by Django 6.0.2 on 2026-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['cluster', 'server_model']},
        ),
        migrations.AlterField(
            model_name='server',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
