# Generated by Django 6.0.2 on 2026-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_server_options_alter_server_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='idrac_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idrac_username',
        ),
        migrations.AddField(
            model_name='server',
            name='idrac_creds',
            field=models.CharField(blank=True, help_text='Format: username/password', max_length=100),
        ),
    ]
