# Generated by Django 6.0.2 on 2026-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_server_idrac_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_type',
            field=models.CharField(blank=True, choices=[('infra', 'Infra'), ('provision', 'Provision'), ('validation', 'Validation')], help_text='Select the category for this cluster', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='gpu_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ib_band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
