# Generated by Django 6.0.2 on 2026-02-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cluster_cluster_type_alter_cluster_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['service_tag', 'server_model']},
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('server_model', models.CharField(max_length=100)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('service_tag', models.CharField(max_length=50, unique=True)),
                ('idrac_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='dashboard.cluster')),
            ],
            options={
                'ordering': ['service_tag', 'server_model'],
            },
        ),
    ]
