# Generated by Django 6.0.2 on 2026-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_server_options_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='rack_no',
            field=models.CharField(blank=True, default='', help_text='Rack number location', max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='current_user',
            field=models.CharField(blank=True, default='', help_text='Current user assigned to this node', max_length=100),
        ),
    ]
