# Generated by Django 6.0.2 on 2026-02-28 17:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20260228_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='idrac_creds',
            field=models.CharField(blank=True, default='', help_text='Format: username/password', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='bmc_mac_address',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='node',
            name='pxe_mac_address',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='node',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
