# Generated by Django 6.0.2 on 2026-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20260228_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='gpu_name',
            field=models.CharField(blank=True, default='', help_text='GPU name/model', max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='gpu_count',
            field=models.IntegerField(default=0, help_text='Number of GPUs'),
        ),
    ]
